name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build (stillaxis-core)
      run: |
        cd ${GITHUB_WORKSPACE}/rust/stillaxis-core
        cargo rustc -- -D warnings

    - name: Build (stillaxis)
      run: |
        cd ${GITHUB_WORKSPACE}/rust/stillaxis
        cargo rustc -- -D warnings

    - name: Run tests (stillaxis-core)
      run: |
        cd ${GITHUB_WORKSPACE}/rust/stillaxis-core
        cargo test --verbose

    - name: Run tests (stillaxis)
      run: |
        cd ${GITHUB_WORKSPACE}/rust/stillaxis
        cargo test --verbose

    - name: Format check (stillaxis-core)
      run: |
        cd ${GITHUB_WORKSPACE}/rust/stillaxis-core
        cargo fmt -- --check

    - name: Format check (stillaxis)
      run: |
        cd ${GITHUB_WORKSPACE}/rust/stillaxis
        cargo fmt -- --check
