name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}/app
        cargo rustc -- -D warnings

    - name: Run tests
      run: |
        cd ${GITHUB_WORKSPACE}/app
        cargo test --verbose

    - name: Format check
      run: |
        cd ${GITHUB_WORKSPACE}/app
        cargo fmt --check
